### ISSUE TITLE
Questions about PRIME_BITLEN and round number

### ISSUE THREAD

**Issue by XuyangSong** [Manta-Network/Plonk-Prototype#4]
https://github.com/Manta-Network/Plonk-Prototype/blob/bae3f952c0caf19b49dd6fff71f3a243d34d57bd/src/poseidon/round_numbers.rs#L7
Can we always use `PRIME_BITLEN=256` to compute round number for different fields?

Another question about round number
Does the round number generated in the repo(rust) still have the same result with reference from the python script [here](https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/9d80ec0473ad7cde5a12f3aac46439ad0da68c0a/code/scripts/calc_round_numbers.py)?
I don't know why I could not get the same result. 

Btw, for generate_parameters_grain_deterministic.sage and poseidonperm_bls381_width3.sage, I can get the same result with rust code even for different fields.

**Comment by BoyuanFeng** [comment]
1. "Can we always use PRIME_BITLEN=256 to compute round numbers for different fields?"

No, you cannot. As specified in the comments (see below), `PRIME_BITLEN=256` is "the number of bits of the Poseidon prime field modulus."

https://github.com/Manta-Network/Plonk-Prototype/blob/bae3f952c0caf19b49dd6fff71f3a243d34d57bd/src/poseidon/round_numbers.rs#L3-L6

2. "Does the round number generated in the repo(rust) still have the same result with reference from the python script [here](https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/9d80ec0473ad7cde5a12f3aac46439ad0da68c0a/code/scripts/calc_round_numbers.py)?"

Yes. For example, if you run "python2 calc_round_numbers.py 762 3 128 1 1", you will have (R_F, R_P) = (8, 55). This matches hardcoded tests: 
https://github.com/Manta-Network/Plonk-Prototype/blob/bae3f952c0caf19b49dd6fff71f3a243d34d57bd/src/poseidon/round_numbers.rs#L101

**Comment by XuyangSong** [comment]
Thanks for your reply.

1. So we'd better not hardcode the `PRIME_BITLEN `, and use `Fr: : size_in_bits()` instead or take another parameter?
2. Oh, I used the wrong sbox_case parameter.

**Comment by BoyuanFeng** [comment]
`So we'd better not hardcode the PRIME_BITLEN , and use Fr: : size_in_bits() instead or take another parameter?`

It is indeed more complex than that. The properties used to compute round numbers also change from the current implementation. You may also need to update alpha. Please check the paper for properly selecting round numbers for other curves.

**Comment by XuyangSong** [comment]
ty, I'll check it.
